name: CI

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

env:
  RUSTFLAGS: -Dwarnings

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        args:
          - ""
          - "--features std"
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --no-default-features ${{ matrix.args }}
  clippy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        args:
          - ""
          - "--features std"
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --no-default-features ${{ matrix.args }}
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
      - uses: actions-rs/cargo@v1
        with:
          toolchain: nightly
          command: rustdoc
          args: --all-features -- --cfg doc_cfg
